{
"schemaVersion": 1,
"id": "${mod_id}",
"version": "${mod_version}",

"name": "${mod_name}",
"description": "${mod_description}",
"authors": [
"${mod_authors}"
],
"contact": {
"homepage": "https://your-homepage.com/",
"sources": "https://github.com/your-repo/",
"issues": "https://github.com/your-repo/issues/"
},

"license": "${mod_license}",
"icon": "assets/${mod_id}/icon.png",

"environment": "*",
"entrypoints": {
"main": [
"com.reclizer.csgobox.CsgoBox"
],
"client": [
"com.reclizer.csgobox.CsgoBoxClient"
],
"cardinal-components": [
"com.reclizer.csgobox.component.ModComponents"
]
},
"mixins": [
"${mod_id}.mixins.json"
],

"depends": {
"fabricloader": ">=${loader_version}",
"fabric-api": "*",
"minecraft": "~${minecraft_version}",
"java": ">=${java_version}"
},
"suggests": {
"another-mod": "*"
}
}